# 2026.4.26 部分解锁premium,音质不能设置为超高(建议登录后再打开脚本,重启app等待脚本生效)
# 原项目地址 https://github.com/app2smile/rules
# 功能: 1.去除播放广告 2.歌手/专辑列表正常展示 3.去除随机播放
  
[filter_local]
#DOMAIN-SUFFIX,spotify.com,REJECT-QUIC
DOMAIN,aet.spotify.com,REJECT

[rewrite_local]

^https:\/\/(spclient\.wg|.*-spclient)\.spotify\.com(:443)?\/pendragon url reject-200

# 屏蔽设置界面会员信息（仅改变显示）
^https:\/\/.*-spclient\.spotify\.com(:443)?\/pam-view-service\/ url reject-200

# 屏蔽 AI DJ
^https:\/\/.*37i9dQZF1EYkqdzj48dyYq.* url reject-200
  


hostname = spclient.wg.spotify.com, *spclient.spotify.com
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ url script-request-header https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-qx-header.js
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$ url script-response-body https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-proto-ev3.js
^https:\/\/(.*-spclient\.spotify\.com(:443)?|spclient\.wg\.spotify\.com)\/gabo-receiver-service url script-request-header https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-gabo.js

# 去广告
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/browsita\/v.\/browse url script-response-body https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-NoSearchAd.js
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/casita\/v.\/home\/default url script-response-body https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-NoHomeAd.js
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/scrollsita\/v.\/scroll\/spotify url script-response-body https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-NoScrollAd.js
